version: 2.1
jobs:
  build_api:
    working_directory: ~/repo/Votify
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout:
          path: ~/repo
      - run: dotnet restore
      - run: dotnet build --configuration Release
      - persist_to_workspace:
          root: Votify.Api/bin/Release
          paths:
            - netcoreapp2.2

  build_app:
    working_directory: ~/repo/votify-reactapp
    docker:
      - image: circleci/node:11.10.0
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: npm run build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo/votify-reactapp
          paths:
            - build

  deploy:
    machine:
      enabled: true
    steps:
      - run: ls
          
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_api
      - build_app
      - deploy:
          requires:
            - build_api
            - build_app
          filters:
            branches:
              only: master
