version: 2.1
jobs:
  build_api:
    working_directory: ~/repo/Votify
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout:
          path: ~/repo
      - run: dotnet restore
      - run: dotnet build --configuration Release
      - persist_to_workspace:
          root: Votify.Api/bin/Release
          paths:
            - netcoreapp2.2

  build_app:
    working_directory: ~/repo/votify-reactapp
    docker:
      - image: circleci/node:11.10.0
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: npm run build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo/votify-reactapp
          paths:
            - build

  deploy:
    docker:
      - image: cibuilds/hugo:0.42.1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys
      - run:
          name: Set up known_hosts
          command: |
            ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
      - run:
          name: Deploy API files
          command: |
            rsync -va --delete /tmp/workspace/netcoreapp2.2/ $SSH_USER@$SSH_HOST:/docker/votify/votify_api/netcoreapp2.2
      - run:
          name: Deploy app files
          command: |
            rsync -va --delete /tmp/workspace/build/ $SSH_USER@$SSH_HOST:/docker/votify/votify_static/build
      - run:
          name: Rebuild/restart containers
          command: |
            ssh $SSH_USER@$SSH_HOST \<<'ENDSSH'
            cd /docker/votify
            docker-compose down
            docker-compose build
            docker-compose up
            ENDSSH

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_api
      - build_app
      - deploy:
          requires:
            - build_api
            - build_app
          filters:
            branches:
              only: master
